# Generated by Django 6.0.3 on 2026-03-18 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sms_opt_in', models.BooleanField(default=False)),
                ('current_state', models.CharField(choices=[('greeting', 'Greeting'), ('intake', 'Patient Intake'), ('reason', 'Reason for Visit'), ('matching', 'Doctor Matching'), ('scheduling', 'Scheduling'), ('confirmation', 'Confirmation'), ('general', 'General Inquiry'), ('completed', 'Completed')], default='greeting', max_length=20)),
                ('matched_doctor_id', models.CharField(blank=True, max_length=50)),
                ('appointment_date', models.CharField(blank=True, max_length=20)),
                ('appointment_time', models.CharField(blank=True, max_length=20)),
                ('reason_for_visit', models.TextField(blank=True)),
                ('voice_call_initiated', models.BooleanField(default=False)),
                ('vapi_call_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_first_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_dob', models.DateField()),
                ('doctor_id', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=200)),
                ('appointment_date', models.CharField(max_length=20)),
                ('appointment_time', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('confirmed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation_email_sent', models.BooleanField(default=False)),
                ('confirmation_sms_sent', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='chat.chatsession')),
            ],
        ),
    ]
